### ISSUE TITLE
NPM publication

### ISSUE THREAD

**Issue by joshuajeschek** [Sipixer/overfast-api#1]
Hey, I would like to use your project but noticed that you haven't published it on npm. Do you plan on doing so? Cheers!

**Comment by Sipixer** [comment]
Hi @joshuajeschek,

Apologies for the delay. The Overfast API Client is now on npm with the new system.

You can find it here: [Overfast API Client on npm](https://www.npmjs.com/package/overfast-api-client).

Thanks for your patience!

**Comment by joshuajeschek** [comment]
nice :)
