### ISSUE TITLE
Error when displaying information about the player

### ISSUE THREAD

**Issue by BL4CklE** [Sipixer/overfast-api#4]
Hi, I found your library here and decided to try to output information about the player, but the error "OverfastClient is not a constructor" appears

**Comment by BL4CklE** [comment]
![image](https://github.com/Sipixer/overfast-api-client/assets/57113246/8b3f2448-8a7e-4459-9ad7-761b7a71690a)

**Comment by Sipixer** [comment]
Hi, Can you share your code and the package versions please ?

**Comment by BL4CklE** [comment]
import { SlashCommandBuilder } from "@discordjs/builders";
import { EmbedBuilder, ActionRowBuilder, ButtonBuilder, PermissionsBitField, ModalBuilder, TextInputComponent, InteractionWebhook, TextInputBuilder, TextInputStyle } from "discord.js";
import { format } from "node:util";
import CONFIG from '../configBot.json' assert { type: "json" };
import { registerSlashCommand } from "../index.js";
import overwatch from 'overwatch-api';
import { OpenWeatherAPI } from "openweather-api-node";
import { QuickDB } from 'quick.db';
import OverfastClient from "overfast-api-client";

registerSlashCommand({
  data: new SlashCommandBuilder()
    .setName("test")
    .setDescription("Test command"),

    async execute(interaction) {

      const overfast = new OverfastClient();

      overfast.players.player("Sipixer#2880").summary().then((summary) => {
      console.log(summary);
      });
    }
})
It test code and screen 
![image](https://github.com/Sipixer/overfast-api-client/assets/57113246/1341b5c0-0728-4b6d-8494-0281381208af)

**Comment by Sipixer** [comment]
What's your Nodejs version ? 
Can you try to execute this code in main context not in execute function ?
```js
const overfast = new OverfastClient();

overfast.players.player("Sipixer#2880").summary().then((summary) => {
console.log(summary);
});
```

**Comment by BL4CklE** [comment]
Node js 21.5.0
Unfortunately, without execute, the command will not work adequately, I checked, the bot goes to the Rate limit

**Comment by Sipixer** [comment]
I have pushed a new version to npm.
Update your package with npm update.
Now import with 
```js
import {OverfastClient} from "overfast-api-client";
```
instead of
```js
import OverfastClient from "overfast-api-client";
```

**Comment by BL4CklE** [comment]
It worked! Thanks bro <3
